name: CICD demo
on:
  workflow_dispatch      #Trigger

jobs:                    #Jobs
  Build:
    runs-on: ubuntu-latest        #Each job should have its on runner
    steps:
      - name: Build step
        run: |
          echo "Welcome ${{vars.MY_NAME}}"

      
      
      
