name: CICD demo
on:
  workflow_dispatch      #Trigger

jobs:                    #Jobs
  Build:
    runs-on: ubuntu-latest        #Each job should have its on runner
    steps:
      - name: Build step
        run: |
          echo "Building started..."
          echo "Building Successful !"
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: testing phase
        run: echo "Testing completed successfully "
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy stage
        run: |
          echo "Deploying the artifacts"
          echo "Deploying Successful !"
      
      
      
