name: GHA demo                      #Define name of the workflow
on: workflow_dispatch               #Define Trigger for manual option

jobs:                               #Define Jobs sections    
  Hello-world:                      #Define name of the job
    runs-on: ubuntu-latest          #Define on which targer or runner you want this job to execute
    steps:                          #Define Steps -> small tasks that make a job
      - name: Hello world step      #Define name of the step
        run: |
          echo "Hellow World"                #Define the Task
          echo "Welcome to GitHub Actions"   #Define multiple commands using "|"
