name: CICD demo
on:
  workflow_dispatch      #Trigger

jobs:                    #Jobs
  Build:
    runs-on: ubuntu-latest        #Each job should have its on runner
    steps:
      - name: checkout stage
        uses: actions/checkout@v4   #Checkout code
      - name:  run file 
        run: cat welcome-nk.html #Start-Process welcome-nk.html   #Run file

      
      
      
