name: CICD
on:
  push:
    branches:
      - main
      
jobs:
  Secrete-test:
    runs-on: ubuntu-latest
    steps:
      - name: Print html content
        run: cat welcome-nk.html

        
        
