name: CICD demo
on:
  [pull_request]      #Trigger

jobs:                    #Jobs
  Build:
    runs-on: ubuntu-latest        #Each job should have its on runner
    steps:
      - name: Build step
        run: |
          echo "Building started..."
          echo "Build Successful !"
  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: testing phase
        run: echo "Test successful"
  Deploy:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy stage
        run: |
          echo "Deploying the artifacts..."
          echo "Deployement Successful !"
      
      
      
